language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx-19mode
  - rbx-2.0.0
  - rbx-head
matrix:
  allow_failures:
    - rvm: rbx-2.0.0
    - rvm: rbx-head
script: rspec
